##connect to database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

##JPA Config
spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

##JWT
jwt.secret = ${jwt_secret}

##Cloudinary
cloud.name = ${cloud_name}
api.key = ${api_key}
api.secret = ${api_secret}
clerk.auth.key = ${clerk_auth_key}

#Request and file size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
